import {
    RiArticleLine,
    RiBarChartBoxLine,
    RiCloudLine,
    RiDashboardLine,
    RiFileList3Line,
    RiFolderImageLine,
    RiGlobalLine,
    RiHome4Line,
    RiImageLine,
    RiInboxLine,
    RiLayoutMasonryLine,
    RiMenu2Line,
    RiPagesLine,
    RiPaletteLine,
    RiQuestionLine,
    RiSearchLine,
    RiServiceLine,
    RiSettings3Line,
    RiStore2Line,
    RiTeamLine,
    RiTestTubeLine,
    RiVipCrownLine,
    RiWindowLine,
} from 'react-icons/ri';

export const navIcons = {
    dashboard: RiDashboardLine,
    website: RiWindowLine,
    content: RiArticleLine,
    services: RiServiceLine,
    portfolio: RiFolderImageLine,
    media: RiImageLine,
    marketing: RiInboxLine,
    seo: RiSearchLine,
    system: RiSettings3Line,
    site: RiGlobalLine,
    'site-seo': RiSearchLine,
    menus: RiMenu2Line,
    theme: RiPaletteLine,
    cloudinary: RiCloudLine,
    'cloudinary-settings': RiCloudLine,
    homepage: RiHome4Line,
    logos: RiImageLine,
    statistics: RiBarChartBoxLine,
    pages: RiPagesLine,
    forms: RiFileList3Line,
    blog: RiArticleLine,
    categories: RiFileList3Line,
    testimonials: RiTestTubeLine,
    faqs: RiQuestionLine,
    team: RiTeamLine,
    packages: RiVipCrownLine,
    contacts: RiInboxLine,
    builder: RiLayoutMasonryLine,
    store: RiStore2Line,
};

export function NavIcon({ name, className = '' }) {
    const Icon = navIcons[name] || RiSettings3Line;
    return <Icon className={className} />;
}
