import {
    RiArticleLine,
    RiBankCardLine,
    RiBarChartBoxLine,
    RiBriefcaseLine,
    RiCalculatorLine,
    RiCalendarCheckLine,
    RiCloudLine,
    RiDashboardLine,
    RiFileList3Line,
    RiFolderImageLine,
    RiGlobalLine,
    RiHome4Line,
    RiImageLine,
    RiInboxLine,
    RiLayoutMasonryLine,
    RiMenu2Line,
    RiPagesLine,
    RiPaletteLine,
    RiQuestionLine,
    RiServiceLine,
    RiSettings3Line,
    RiStore2Line,
    RiTeamLine,
    RiTestTubeLine,
    RiVipCrownLine,
    RiWindowLine,
} from 'react-icons/ri';

export const navIcons = {
    dashboard: RiDashboardLine,
    website: RiWindowLine,
    content: RiArticleLine,
    business: RiStore2Line,
    services: RiServiceLine,
    portfolio: RiFolderImageLine,
    media: RiImageLine,
    marketing: RiInboxLine,
    system: RiSettings3Line,
    settings: RiSettings3Line,
    access: RiSettings3Line,
    users: RiTeamLine,
    roles: RiFileList3Line,
    site: RiGlobalLine,
    menus: RiMenu2Line,
    theme: RiPaletteLine,
    cloudinary: RiCloudLine,
    homepage: RiHome4Line,
    logos: RiImageLine,
    statistics: RiBarChartBoxLine,
    pages: RiPagesLine,
    forms: RiFileList3Line,
    blog: RiArticleLine,
    categories: RiFileList3Line,
    testimonials: RiTestTubeLine,
    faqs: RiQuestionLine,
    team: RiTeamLine,
    packages: RiVipCrownLine,
    contacts: RiInboxLine,
    leads: RiInboxLine,
    sales: RiBarChartBoxLine,
    quotes: RiCalculatorLine,
    proposals: RiFileList3Line,
    invoices: RiFileList3Line,
    bookings: RiCalendarCheckLine,
    'booking-settings': RiCalendarCheckLine,
    'payment-settings': RiBankCardLine,
    careers: RiBriefcaseLine,
    'audit-logs': RiFileList3Line,
    builder: RiLayoutMasonryLine,
    store: RiStore2Line,
};

export function NavIcon({ name, className = '' }) {
    const Icon = navIcons[name] || RiSettings3Line;
    return <Icon className={className} />;
}
