<?php

use App\Http\Controllers\Admin\AdminUserController;
use App\Http\Controllers\Admin\ContentController;
use App\Http\Controllers\Admin\CloudinaryController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\FormBuilderController;
use App\Http\Controllers\Admin\LeadController;
use App\Http\Controllers\Admin\MediaController;
use App\Http\Controllers\Admin\NotificationController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\PageBuilderController;
use App\Http\Controllers\Admin\SiteSettingsController;
use App\Http\Controllers\Admin\ThemeController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\Admin\AuditLogController;
use App\Http\Controllers\Admin\BookingController as AdminBookingController;
use App\Http\Controllers\Admin\BookingSettingsController;
use App\Http\Controllers\Admin\PaymentSettingsController;
use App\Http\Controllers\Admin\InvoiceController;
use App\Http\Controllers\Admin\ProposalController;
use App\Http\Controllers\Admin\QuoteTypeController;
use App\Http\Controllers\Portal\PortalController;
use App\Http\Controllers\Portal\PortalInvoiceController;
use App\Http\Controllers\Portal\PortalMeetingController;
use App\Http\Controllers\Portal\PortalProposalController;
use App\Http\Controllers\Public\BookingController;
use App\Http\Controllers\Public\FormSubmissionController;
use App\Http\Controllers\Public\PaymentCallbackController;
use App\Http\Controllers\Public\QuoteController;
use App\Http\Controllers\Public\SiteController;
use App\Http\Controllers\Portal\PortalPaymentController;
use Illuminate\Support\Facades\Route;

Route::get('/', [SiteController::class, 'home'])->name('home');
Route::get('/about', [SiteController::class, 'about'])->name('about');
Route::get('/services', [SiteController::class, 'services'])->name('services.index');
Route::get('/services/{service:slug}', [SiteController::class, 'service'])->name('services.show');
Route::get('/packages', [SiteController::class, 'packages'])->name('packages.index');
Route::get('/portfolio', [SiteController::class, 'portfolio'])->name('portfolio.index');
Route::get('/portfolio/{portfolio:slug}', [SiteController::class, 'project'])->name('portfolio.show');
Route::get('/blog', [SiteController::class, 'blog'])->name('blog.index');
Route::get('/blog/{post:slug}', [SiteController::class, 'post'])->name('blog.show');
Route::get('/careers', [SiteController::class, 'careers'])->name('careers.index');
Route::get('/careers/{jobOpening:slug}', [SiteController::class, 'career'])->name('careers.show');
Route::post('/careers/{jobOpening:slug}/apply', [SiteController::class, 'applyCareer'])->name('careers.apply');
Route::get('/contact', [SiteController::class, 'contact'])->name('contact');
Route::post('/contact', [SiteController::class, 'submitContact'])->name('contact.submit');
Route::post('/forms/{form:shortcode}', [FormSubmissionController::class, 'store'])->name('forms.submit');
Route::get('/quote', [QuoteController::class, 'show'])->name('quote');
Route::post('/quote/estimate', [QuoteController::class, 'estimate'])->name('quote.estimate');
Route::post('/quote', [QuoteController::class, 'submit'])->name('quote.submit');
Route::get('/book', [BookingController::class, 'show'])->name('book');
Route::get('/book/slots', [BookingController::class, 'slots'])->name('book.slots');
Route::post('/book', [BookingController::class, 'store'])->name('book.submit');
Route::get('/sitemap.xml', [SiteController::class, 'sitemap'])->name('sitemap');
Route::get('/robots.txt', [SiteController::class, 'robots'])->name('robots');
Route::get('/login', [AuthController::class, 'login'])->middleware('guest')->name('login');
Route::post('/login', [AuthController::class, 'authenticate'])->middleware('guest')->name('login.authenticate');
Route::post('/logout', [AuthController::class, 'logout'])->middleware('auth')->name('logout');

Route::prefix('payments')->name('payments.')->group(function () {
    Route::get('/bkash/callback/{transaction}', [PaymentCallbackController::class, 'bkash'])->name('bkash.callback');
    Route::get('/eps/success/{transaction}', [PaymentCallbackController::class, 'epsSuccess'])->name('eps.success');
    Route::get('/eps/fail/{transaction}', [PaymentCallbackController::class, 'epsFail'])->name('eps.fail');
    Route::get('/eps/cancel/{transaction}', [PaymentCallbackController::class, 'epsCancel'])->name('eps.cancel');
    Route::post('/eps/ipn', [PaymentCallbackController::class, 'epsIpn'])->name('eps.ipn');
});

Route::prefix('portal')->middleware(['auth', 'client.account'])->name('portal.')->group(function () {
    Route::get('/', [PortalController::class, 'dashboard'])->name('dashboard');
    Route::get('/proposals', [PortalProposalController::class, 'index'])->name('proposals.index');
    Route::get('/proposals/{proposal}', [PortalProposalController::class, 'show'])->name('proposals.show');
    Route::post('/proposals/{proposal}/respond', [PortalProposalController::class, 'respond'])->name('proposals.respond');
    Route::get('/proposals/{proposal}/pdf', [PortalProposalController::class, 'pdf'])->name('proposals.pdf');
    Route::get('/invoices', [PortalInvoiceController::class, 'index'])->name('invoices.index');
    Route::get('/invoices/{invoice}', [PortalInvoiceController::class, 'show'])->name('invoices.show');
    Route::get('/invoices/{invoice}/pdf', [PortalInvoiceController::class, 'pdf'])->name('invoices.pdf');
    Route::post('/invoices/{invoice}/pay/bkash', [PortalPaymentController::class, 'payBkash'])->name('invoices.pay.bkash');
    Route::post('/invoices/{invoice}/pay/eps', [PortalPaymentController::class, 'payEps'])->name('invoices.pay.eps');
    Route::get('/meetings', [PortalMeetingController::class, 'index'])->name('meetings.index');
});

Route::prefix('admin')->middleware(['auth', 'admin.permission'])->name('admin.')->group(function () {
    Route::get('/', DashboardController::class)->name('dashboard');
    Route::redirect('/settings', '/admin/site/settings');
    Route::get('/site/settings', [SiteSettingsController::class, 'edit'])->name('site.edit');
    Route::put('/site/settings', [SiteSettingsController::class, 'update'])->name('site.update');
    Route::post('/site/settings', [SiteSettingsController::class, 'update']);
    Route::get('/menus', [MenuController::class, 'edit'])->name('menus.edit');
    Route::put('/menus', [MenuController::class, 'update'])->name('menus.update');
    Route::post('/menus', [MenuController::class, 'update']);
    Route::get('/cloudinary/settings', [CloudinaryController::class, 'edit'])->name('cloudinary.edit');
    Route::put('/cloudinary/settings', [CloudinaryController::class, 'update'])->name('cloudinary.update');
    Route::post('/cloudinary/test', [CloudinaryController::class, 'test'])->name('cloudinary.test');
    Route::get('/theme/settings', [ThemeController::class, 'edit'])->name('theme.edit');
    Route::put('/theme/settings', [ThemeController::class, 'update'])->name('theme.update');
    Route::get('/media', [MediaController::class, 'index'])->name('media.index');
    Route::get('/media/picker', [MediaController::class, 'picker'])->name('media.picker');
    Route::post('/editor/upload', [MediaController::class, 'editorUpload'])->name('editor.upload');
    Route::post('/media', [MediaController::class, 'store'])->name('media.store');
    Route::delete('/media/bulk', [MediaController::class, 'bulkDestroy'])->name('media.bulk-destroy');
    Route::put('/media/{mediaItem}', [MediaController::class, 'update'])->name('media.update');
    Route::delete('/media/{mediaItem}', [MediaController::class, 'destroy'])->name('media.destroy');
    Route::get('/pages/create', [PageBuilderController::class, 'create'])->name('pages.create');
    Route::post('/pages', [PageBuilderController::class, 'store'])->name('pages.store');
    Route::get('/pages/{page}/builder', [PageBuilderController::class, 'builder'])->name('pages.builder');
    Route::put('/pages/{page}/builder', [PageBuilderController::class, 'update'])->name('pages.builder.update');
    Route::get('/forms', [FormBuilderController::class, 'index'])->name('forms.index');
    Route::get('/forms/create', [FormBuilderController::class, 'create'])->name('forms.create');
    Route::post('/forms', [FormBuilderController::class, 'store'])->name('forms.store');
    Route::delete('/forms/bulk', [FormBuilderController::class, 'bulkDestroy'])->name('forms.bulk-destroy');
    Route::delete('/form-submissions/bulk', [FormBuilderController::class, 'bulkDestroySubmissions'])->name('forms.submissions.bulk-destroy');
    Route::get('/forms/{form}/edit', [FormBuilderController::class, 'edit'])->name('forms.edit');
    Route::put('/forms/{form}', [FormBuilderController::class, 'update'])->name('forms.update');
    Route::delete('/forms/{form}', [FormBuilderController::class, 'destroy'])->name('forms.destroy');
    Route::get('/forms/{form}/submissions', [FormBuilderController::class, 'submissions'])->name('forms.submissions');
    Route::post('/form-submissions/{submission}/read', [FormBuilderController::class, 'markRead'])->name('forms.submissions.read');
    Route::get('/roles', [RoleController::class, 'index'])->name('roles.index');
    Route::get('/roles/create', [RoleController::class, 'create'])->name('roles.create');
    Route::post('/roles', [RoleController::class, 'store'])->name('roles.store');
    Route::delete('/roles/bulk', [RoleController::class, 'bulkDestroy'])->name('roles.bulk-destroy');
    Route::get('/roles/{role}/edit', [RoleController::class, 'edit'])->name('roles.edit');
    Route::put('/roles/{role}', [RoleController::class, 'update'])->name('roles.update');
    Route::delete('/roles/{role}', [RoleController::class, 'destroy'])->name('roles.destroy');
    Route::get('/users', [AdminUserController::class, 'index'])->name('users.index');
    Route::get('/users/create', [AdminUserController::class, 'create'])->name('users.create');
    Route::post('/users', [AdminUserController::class, 'store'])->name('users.store');
    Route::delete('/users/bulk', [AdminUserController::class, 'bulkDestroy'])->name('users.bulk-destroy');
    Route::get('/users/{user}/edit', [AdminUserController::class, 'edit'])->name('users.edit');
    Route::put('/users/{user}', [AdminUserController::class, 'update'])->name('users.update');
    Route::post('/users/{user}/regenerate-password', [AdminUserController::class, 'regeneratePassword'])->name('users.regenerate-password');
    Route::delete('/users/{user}', [AdminUserController::class, 'destroy'])->name('users.destroy');
    Route::get('/quotes', [QuoteTypeController::class, 'index'])->name('quotes.index');
    Route::get('/quotes/{quoteType}/edit', [QuoteTypeController::class, 'edit'])->name('quotes.edit');
    Route::put('/quotes/{quoteType}', [QuoteTypeController::class, 'update'])->name('quotes.update');
    Route::get('/proposals', [ProposalController::class, 'index'])->name('proposals.index');
    Route::get('/proposals/create', [ProposalController::class, 'create'])->name('proposals.create');
    Route::post('/proposals', [ProposalController::class, 'store'])->name('proposals.store');
    Route::get('/proposals/{proposal}/edit', [ProposalController::class, 'edit'])->name('proposals.edit');
    Route::put('/proposals/{proposal}', [ProposalController::class, 'update'])->name('proposals.update');
    Route::delete('/proposals/{proposal}', [ProposalController::class, 'destroy'])->name('proposals.destroy');
    Route::get('/proposals/{proposal}/pdf', [ProposalController::class, 'pdf'])->name('proposals.pdf');
    Route::post('/proposals/{proposal}/send', [ProposalController::class, 'send'])->name('proposals.send');
    Route::get('/invoices', [InvoiceController::class, 'index'])->name('invoices.index');
    Route::get('/invoices/create', [InvoiceController::class, 'create'])->name('invoices.create');
    Route::post('/invoices', [InvoiceController::class, 'store'])->name('invoices.store');
    Route::get('/invoices/{invoice}/edit', [InvoiceController::class, 'edit'])->name('invoices.edit');
    Route::put('/invoices/{invoice}', [InvoiceController::class, 'update'])->name('invoices.update');
    Route::delete('/invoices/{invoice}', [InvoiceController::class, 'destroy'])->name('invoices.destroy');
    Route::get('/invoices/{invoice}/pdf', [InvoiceController::class, 'pdf'])->name('invoices.pdf');
    Route::post('/invoices/{invoice}/payments', [InvoiceController::class, 'storePayment'])->name('invoices.payments.store');
    Route::get('/audit-logs', [AuditLogController::class, 'index'])->name('audit-logs.index');
    Route::get('/bookings', [AdminBookingController::class, 'index'])->name('bookings.index');
    Route::get('/bookings/settings', [BookingSettingsController::class, 'edit'])->name('bookings.settings');
    Route::put('/bookings/settings', [BookingSettingsController::class, 'update'])->name('bookings.settings.update');
    Route::get('/payments/settings', [PaymentSettingsController::class, 'edit'])->name('payments.settings');
    Route::put('/payments/settings', [PaymentSettingsController::class, 'update'])->name('payments.settings.update');
    Route::get('/bookings/{booking}', [AdminBookingController::class, 'show'])->name('bookings.show');
    Route::put('/bookings/{booking}', [AdminBookingController::class, 'update'])->name('bookings.update');
    Route::delete('/bookings/{booking}', [AdminBookingController::class, 'destroy'])->name('bookings.destroy');
    Route::get('/leads', [LeadController::class, 'index'])->name('leads.index');
    Route::delete('/leads/bulk', [LeadController::class, 'bulkDestroy'])->name('leads.bulk-destroy');
    Route::get('/leads/{lead}', [LeadController::class, 'show'])->name('leads.show');
    Route::put('/leads/{lead}', [LeadController::class, 'update'])->name('leads.update');
    Route::delete('/leads/{lead}', [LeadController::class, 'destroy'])->name('leads.destroy');
    Route::post('/leads/{lead}/notes', [LeadController::class, 'storeNote'])->name('leads.notes.store');
    Route::post('/leads/{lead}/followups', [LeadController::class, 'storeFollowup'])->name('leads.followups.store');
    Route::post('/leads/{lead}/followups/{followup}/complete', [LeadController::class, 'completeFollowup'])->name('leads.followups.complete');
    Route::post('/leads/{lead}/invite-portal', [LeadController::class, 'invitePortal'])->name('leads.invite-portal');
    Route::post('/leads/{lead}/regenerate-portal-password', [LeadController::class, 'regeneratePortalPassword'])->name('leads.regenerate-portal-password');
    Route::get('/notifications', [NotificationController::class, 'index'])->name('notifications.index');
    Route::get('/notifications/feed', [NotificationController::class, 'feed'])->name('notifications.feed');
    Route::post('/notifications/read-all', [NotificationController::class, 'markAllRead'])->name('notifications.read-all');
    Route::post('/notifications/{notification}/read', [NotificationController::class, 'markRead'])->name('notifications.read');
    Route::redirect('/contacts', '/admin/leads');
    Route::get('/contacts/{id}', fn (int $id) => redirect("/admin/leads/{$id}"));
    Route::delete('/{module}/bulk', [ContentController::class, 'bulkDestroy'])->name('modules.bulk-destroy');
    Route::get('/{module}', [ContentController::class, 'index'])->name('modules.index');
    Route::get('/{module}/create', [ContentController::class, 'create'])->name('modules.create');
    Route::post('/{module}', [ContentController::class, 'store'])->name('modules.store');
    Route::get('/{module}/{id}/edit', [ContentController::class, 'edit'])->name('modules.edit');
    Route::put('/{module}/{id}', [ContentController::class, 'update'])->name('modules.update');
    Route::delete('/{module}/{id}', [ContentController::class, 'destroy'])->name('modules.destroy');
});

Route::get('/{page:slug}', [SiteController::class, 'page'])->name('pages.show');
